# Generated by Django 6.0.3 on 2026-03-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad de Pasajeros')),
            ],
            options={
                'verbose_name': 'Autobús',
                'verbose_name_plural': 'Autobuses',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('dpi', models.CharField(max_length=13, unique=True, verbose_name='DPI')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100, verbose_name='Origen')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(verbose_name='Fecha y Hora de Salida')),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.autobus', verbose_name='Autobús')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveIntegerField(verbose_name='Número de Asiento')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.pasajero', verbose_name='Pasajero')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='transporte.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'unique_together': {('viaje', 'numero_asiento')},
            },
        ),
    ]
